# Generated by Django 2.2.3 on 2022-04-09 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileno', models.CharField(max_length=18)),
                ('filename', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField()),
                ('isapprove', models.CharField(max_length=1)),
                ('approve_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'approve_log',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileno', models.CharField(max_length=18)),
                ('filename', models.CharField(max_length=200)),
                ('filepath', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('isapprove', models.CharField(default='0', max_length=1)),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
