# Generated by Django 2.2.3 on 2022-04-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_hash',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
