# Generated by Django 2.2.3 on 2022-04-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0002_auto_20220412_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvelog',
            name='approve_person',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
