# Generated by Django 2.2.3 on 2022-04-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0003_approvelog_approve_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('transaction', models.TextField(max_length=200)),
                ('proof', models.IntegerField()),
                ('pre_hash', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'blockchain_log',
            },
        ),
    ]
