# Generated by Django 2.2.3 on 2022-04-09 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=100)),
                ('password_salt', models.CharField(max_length=50)),
                ('department', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserOperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=20)),
                ('do_type', models.CharField(max_length=20)),
                ('department', models.IntegerField(default=1)),
                ('fileno', models.CharField(max_length=18)),
                ('filename', models.CharField(max_length=200)),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Operate_log',
            },
        ),
    ]
